### ISSUE TITLE
Update FeedMeRedirect to match Feedmes Element definition

### ISSUE THREAD

**Issue by gglnx** [venveo/craft-redirect#56]
If try run Feedme I get the following error:

> Declaration of venveo\redirect\elements\FeedMeRedirect::save($element, $settings) must be compatible with craft\feedme\base\Element::save($element, $settings): bool

I'm using the `4.0.0-beta.3` with Feedme version `5.0.5`.

**Comment by Mosnar** [comment]
Tagged 4.0.0-beta.4
