### ISSUE TITLE
JavaScript error after creation of a redirect

### ISSUE THREAD

**Issue by gglnx** [venveo/craft-redirect#58]
If I create a redirect via the slide-out on the redirects index I get following javascript error after saving:

<img width="998" alt="SCR-20230208-jwi" src="https://user-images.githubusercontent.com/23519/217541649-82a812ae-7cea-4eb9-ab2c-a133b8515819.png">

* Craft 4.3.8
* Plugin 4.0.0-beta.3

**Comment by Mosnar** [comment]
Tagged 4.0.0-beta.4
