### ISSUE TITLE
Too early call for user identity throws warnings

### ISSUE THREAD

**Issue by gglnx** [venveo/craft-redirect#60]
`attachTemplateHooks()` in the `Plugins.php` checks if an user exists and if they have sufficient permissions. This call happends before Craft is fully initialized and a warning with a complete dump of the current env is written to the logs. This happends on every control panel request.

> 2023-02-08 16:31:21 [web.WARNING] [craft\elements\db\ElementQuery::prepare] Element query executed before Craft is fully initialized. {"memory":4857864}
> 2023-02-08 16:31:21 [web.WARNING] [application] Request context: {"userId":17,"vars":{"_GET":[],"_POST":[],"_COOKIE":{"…

Can you delay attachTemplateHooks() until `WebApplication::EVENT_INIT` fired?

* Craft 4.3.8
* Plugin 4.0.0-beta.3

**Comment by Mosnar** [comment]
Tagged 4.0.0-beta.4
