### ISSUE TITLE
Redirects don't work on sites with path in base URL

### ISSUE THREAD

**Issue by gglnx** [venveo/craft-redirect#61]
If a site contains a path inside its base URL `venveo\redirect\services\Redirects::handle404()` fails to find the redirect because `$fullPath` isn't stripped of the site base path.

**Comment by Mosnar** [comment]
Is this for Craft 4 or Craft 3?

**Comment by gglnx** [comment]
Craft 4. Using your latest beta 3.

**Comment by Mosnar** [comment]
Tagged 4.0.0-beta.4
